---
- name: "Create download directory"
  file:
    path: "{{ golang_download_dir }}"
    state: directory

- name: "Create golang install directories"
  file:
    path: "{{ golang_install_dir }}"
    state: directory
    owner: root
    group: root

- name: "Download and unarchive golang package"
  unarchive:
    remote_src: yes
    dest: "{{ golang_download_dir }}"
    src: "{{ golang_url }}"